[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cheb3"
version = "0.5.2"
authors = [{name = "YanhuiJessica",email = "y4nhv1@gmail.com"}]
description = "Web3 CTF tool based on web3.py"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "web3>=6.0.0",
  "py-solc-x",
  "loguru",
]
classifiers = [
  "Development Status :: 3 - Alpha",

  "License :: OSI Approved :: MIT License",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]

[project.urls]
"Homepage" = "https://github.com/YanhuiJessica/cheb3"
"Source" = "https://github.com/YanhuiJessica/cheb3"
"Bug Reports" = "https://github.com/YanhuiJessica/cheb3/issues"