name: Testing Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_utils:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python ${{ matrix.python-version }} test utils
        run: |
          python3 -m pytest tests/utils